[config]
schemaVersion = "0.0.1"

[package]
namespace = "madkarma"
name = "MuteIntroGuy"
versionNumber = "1.0.0"
description = "Get mogged by landmines"
websiteUrl = "https://github.com/madkarmaa/MuteIntroGuy"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "../build"


[[build.copy]]
source = "./madkarma.MuteIntroGuy.dll"
target = "./plugin/"


[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company", ]
[publish.categories]
lethal-company = [ "bepinex", "audio", "clientside", "mods" ]